"""
The following keyCodes are available, but maybe not all work for your TV:

Source: http://wiki.samygo.tv/index.php5/Key_codes
"""

# Key Name | Index | Code | BD-IR Code
KEY_CODES = [
("KEY_MTS",                          "00",   "68",   "CA"), # Dual
("KEY_SOURCE",                       "01",   "1A",   ""),
("BD_KEY_POWER",                     "02",   "60",   "91"),
("KEY_SLEEP",                        "03",   "61",   ""),
("KEY_1",                            "04",   "65",   "81"),
("KEY_2",                            "05",   "62",   "82"),
("KEY_3",                            "06",   "06",   "83"),
("KEY_VOLUP",                        "07",   "07",   ""),
("KEY_4",                            "08",   "08",   "84"),
("KEY_5",                            "09",   "09",   "85"),
("KEY_6",                            "0A",   "0A",   "86"),
("KEY_VOLDOWN",                      "0B",   "0B",   ""),
("KEY_7",                            "0C",   "0C",   "87"),
("KEY_8",                            "0D",   "0D",   "88"),
("KEY_9",                            "0E",   "0E",   "89"),
("KEY_MUTE",                         "0F",   "0F",   ""),
("KEY_CHDOWN",                       "10",   "10",   "c6"),
("KEY_0",                            "11",   "11",   "80"),
("KEY_CHUP",                         "12",   "12",   "C5"),
("KEY_PRECH",                        "13",   "13",   "C6"),
("KEY_GREEN",                        "14",   "14",   "C0"),
("KEY_YELLOW",                       "15",   "15",   "76"),
("KEY_CYAN",                         "16",   "16",   "42"),
("KEY_BLUE",                         "16",   "16",   "42"), # Proxy for KEY_CYAN
("KEY_VAL_23",                       "17",   "17",   "C4"),
("KEY_VAL_24",                       "18",   "18",   ""),
("KEY_ADDDEL",                       "19",   "19",   ""),
("KEY_MENU",                         "1A",   "01",   ""),
("KEY_TV",                           "1B",   "1B",   ""),
("KEY_VAL_28",                       "1C",   "1C",   ""),
("KEY_VAL_29",                       "1D",   "1D",   ""),
("KEY_VAL_30",                       "1E",   "FD",   ""),
("KEY_INFO",                         "1F",   "1F",   "41"),
("KEY_PIP_ONOFF",                    "20",   "20",   "CB"),
("KEY_PIP_SWAP",                     "21",   "21",   ""),
("KEY_VAL_34",                       "22",   "22",   ""),
("KEY_PLUS100",                      "23",   "23",   ""), # (acts as "-")
("KEY_VAL_36",                       "24",   "24",   ""),
("KEY_CAPTION",                      "25",   "25",   ""),
("KEY_VAL_38",                       "26",   "26",   ""),
("KEY_AD",                           "27",   "27",   ""),
("KEY_PMODE",                        "28",   "28",   ""), # IMAGE MODE (first open menu and next mode on repeat)
("KEY_VAL_41",                       "29",   "29",   ""),
("KEY_VAL_42",                       "2A",   "2A",   ""),
("KEY_VAL_43",                       "2B",   "2B",   ""),
("KEY_TTX_MIX",                      "2C",   "2C",   "8F"),
("KEY_EXIT",                         "2D",   "2D",   "05"),
("KEY_VAL_43",                       "2E",   "2E",   ""),
("KEY_PIP_SIZE",                     "2F",   "2F",   ""),
("KEY_MAGIC_CHANNEL",                "30",   "30",   ""),
("KEY_PIP_SCAN",                     "31",   "31",   ""),
("KEY_PIP_CHUP",                     "32",   "32",   ""),
("KEY_PIP_CHDOWN",                   "33",   "33",   ""),
("KEY_DEVICE_CONNECT",               "34",   "34",   ""),
("KEY_HELP",                         "35",   "35",   ""),
("KEY_ANTENA",                       "36",   "36",   ""),
("KEY_CONVERGENCE",                  "37",   "37",   ""), # open/close web browser (UN40F5500)
("KEY_11",                           "38",   "38",   ""),
("KEY_12",                           "39",   "39",   "93"),
("KEY_AUTO_PROGRAM",                 "3A",   "3A",   ""),
("KEY_FACTORY",                      "3B",   "3B",   ""), # removed on last firmware
("KEY_3SPEED",                       "3C",   "3C",   ""), # removed on last firmware
("KEY_RSURF",                        "3D",   "3D",   ""),
("KEY_ASPECT",                       "3E",   "3E",   ""),
("KEY_TOPMENU",                      "3F",   "3F",   ""),
("KEY_GAME",                         "40",   "40",   ""),
("KEY_QUICK_REPLAY",                 "41",   "41",   ""),
("KEY_STILL_PICTURE",                "42",   "42",   ""),
("KEY_DTV",                          "43",   "43",   ""),
("KEY_FAVCH",                        "44",   "44",   ""),
("KEY_REWIND",                       "45",   "45",   "9C"),
("KEY_STOP",                         "46",   "46",   "A2"),
("KEY_PLAY",                         "47",   "47",   "A0"),
("KEY_FF",                           "48",   "48",   "9E"),
("KEY_REC",                          "49",   "49",   "C2"),
("KEY_PAUSE",                        "4A",   "4A",   "A3"),
("KEY_TOOLS",                        "4B",   "4B",   "09"),
("KEY_INSTANT_REPLAY",               "4C",   "4C",   ""),
("KEY_LINK",                         "4D",   "4D",   ""),
("KEY_FF_",                          "4E",   "4E",   "A1"),
("KEY_GUIDE",                        "4F",   "4F",   "47"),
("KEY_REWIND_",                      "50",   "50",   "9F"),
("KEY_ANGLE",                        "51",   "51",   ""),
("KEY_RESERVED1",                    "52",   "52",   ""),
("KEY_ZOOM1",                        "53",   "53",   ""),
("KEY_PROGRAM",                      "54",   "54",   ""),
("KEY_BOOKMARK",                     "55",   "55",   ""),
("KEY_DISC_MENU",                    "56",   "56",   "94"),
("KEY_PRINT",                        "57",   "57",   ""),
("KEY_RETURN",                       "58",   "58",   "95"),
("KEY_SUB_TITLE",                    "59",   "59",   "C9"),
("KEY_CLEAR",                        "5A",   "5A",   ""),
("KEY_VCHIP",                        "5B",   "5B",   ""),
("KEY_REPEAT",                       "5C",   "5C",   ""),
("KEY_DOOR",                         "5D",   "5D",   ""),
("KEY_OPEN",                         "5E",   "5E",   "8C"),
("KEY_WHEEL_LEFT",                   "5F",   "5F",   ""),
("KEY_UP",                           "60",   "02",   "97"),
("KEY_DOWN",                         "61",   "03",   "98"),
("KEY_RIGHT",                        "62",   "05",   "99"),
("KEY_DMA",                          "63",   "63",   ""),
("KEY_TURBO",                        "64",   "EF",   "CD"),
("KEY_LEFT",                         "65",   "04",   "9A"),
("KEY_FM_RADIO",                     "66",   "66",   ""),
("KEY_DVR_MENU",                     "67",   "67",   ""),
("KEY_ENTER",                        "68",   "00",   "9B"),
("KEY_PCMODE",                       "69",   "69",   ""),
("KEY_TTX_SUBFACE",                  "6A",   "6A",   ""),
("KEY_CH_LIST",                      "6B",   "6B",   "03"),
("KEY_RED",                          "6C",   "6C",   "90"),
("KEY_DNIe",                         "6D",   "6D",   ""),
("KEY_SRS",                          "6E",   "6E",   ""), # DTS TruSurround
("KEY_CONVERT_AUDIO_MAINSUB",        "6F",   "6F",   ""),
("KEY_MDC",                          "70",   "70",   ""),
("KEY_SEFFECT",                      "71",   "71",   ""),
("KEY_DVR",                          "72",   "72",   "CC"),
("KEY_DTV_SIGNAL",                   "73",   "F0",   "C8"),
("KEY_LIVE",                         "74",   "74",   ""),
("KEY_PERPECT_FOCUS",                "75",   "75",   ""),
("KEY_HOME",                         "76",   "76",   ""),
("KEY_ESAVING",                      "77",   "77",   ""),
("KEY_WHEEL_RIGHT",                  "78",   "78",   ""),
("KEY_CONTENTS",                     "79",   "79",   "8B"),
("KEY_VCR_MODE",                     "7A",   "7A",   ""),
("KEY_CATV_MODE",                    "7B",   "7B",   ""),
("KEY_DSS_MODE",                     "7C",   "7C",   ""),
("KEY_TV_MODE",                      "7D",   "7D",   ""),
("KEY_DVD_MODE",                     "7E",   "7E",   ""),
("KEY_STB_MODE",                     "7F",   "7F",   ""),
("KEY_CALLER_ID",                    "80",   "80",   "0B"),
("KEY_SCALE",                        "81",   "81",   ""),
("KEY_ZOOM_MOVE",                    "82",   "82",   ""),
("KEY_CLOCK_DISPLAY",                "83",   "83",   ""),
("KEY_AV1",                          "84",   "84",   ""),
("KEY_SVIDEO1",                      "85",   "85",   ""),
("KEY_COMPONENT1",                   "86",   "86",   ""),
("KEY_SETUP_CLOCK_TIMER",            "87",   "87",   ""),
("KEY_COMPONENT2",                   "88",   "88",   ""),
("KEY_MAGIC_BRIGHT",                 "89",   "89",   ""),
("KEY_DVI",                          "8A",   "8A",   ""),
("KEY_HDMI",                         "8B",   "8B",   ""),
("KEY_W_LINK",                       "8C",   "8C",   ""), # Media P
("KEY_DTV_LINK",                     "8D",   "8D",   ""),
("KEY_VAL_142",                      "8E",   "8E",   ""),
("KEY_APP_LIST",                     "8F",   "8F",   ""),
("KEY_BACK_MHP",                     "90",   "90",   ""),
("KEY_ALT_MHP",                      "91",   "91",   ""),
("KEY_DNSe",                         "92",   "92",   ""),
("KEY_RSS",                          "93",   "93",   "08"), # Internet
("KEY_INTERNET",                     "93",   "93",   "08"), # Proxy for KEY_RSS
("KEY_ENTERTAINMENT",                "94",   "94",   ""),
("KEY_ID_INPUT",                     "95",   "95",   ""),
("KEY_ID_SETUP",                     "96",   "96",   ""),
("KEY_ANYNET",                       "97",   "97",   ""),
("KEY_POWEROFF",                     "98",   "98",   ""),
("KEY_POWERON",                      "99",   "99",   ""),
("KEY_ANYVIEW",                      "9A",   "9A",   ""),
("KEY_MS",                           "9B",   "9B",   ""),
("KEY_MORE",                         "9C",   "9C",   ""),
("KEY_PANNEL_POWER",                 "9D",   "B1",   ""),
("KEY_PANNEL_CHUP",                  "9E",   "B2",   ""),
("KEY_PANNEL_CHDOWN",                "9F",   "B3",   "C7"),
("KEY_PANNEL_VOLUP",                 "A0",   "FB",   ""),
("KEY_PANNEL_VOLDOW",                "A1",   "107",  ""),
("KEY_PANNEL_ENTER",                 "A2",   "108",  ""),
("KEY_PANEL_MENU",                   "A3",   "109",  ""),
("KEY_PANNEL_SOURCE",                "A4",   "103",  ""),
("KEY_AV2",                          "A5",   "105",  ""),
("KEY_AV3",                          "A6",   "106",  ""),
("KEY_SVIDEO2",                      "A7",   "10A",  ""),
("KEY_SVIDEO3",                      "A8",   "FFFF", ""),
("KEY_ZOOM2",                        "A9",   "FFFF", ""),
("KEY_PANORAMA",                     "AA",   "FFFF", ""),
("KEY_4_3",                          "AB",   "FFFF", ""),
("KEY_16_9",                         "AC",   "FFFF", ""),
("KEY_DYNAMIC",                      "AD",   "FFFF", ""),
("KEY_STANDARD",                     "AE",   "FFFF", ""),
("KEY_MOVIE1",                       "AF",   "FFFF", ""),
("KEY_CUSTOM",                       "B0",   "F2",   ""),
("KEY_AUTO_ARC_RESET",               "B1",   "F3",   ""),
("KEY_AUTO_ARC_LNA_ON",              "B2",   "FFFF", ""),
("KEY_AUTO_ARC_LNA_OFF",             "B3",   "FFFF", ""),
("KEY_AUTO_ARC_ANYNET_MODE_OK",      "B4",   "FFFF", ""),
("KEY_AUTO_ARC_ANYNET_AUTO_START",   "B5",   "FFFF", ""),
("KEY_AUTO_FORMAT",                  "B6",   "FFFF", ""),
("KEY_DNET",                         "B7",   "FFFF", ""),
("KEY_HDMI1",                        "B8",   "FFFF", ""),
("KEY_AUTO_ARC_CAPTION_ON",          "B9",   "FFFF", ""),
("KEY_AUTO_ARC_CAPTION_OFF",         "BA",   "FFFF", ""),
("KEY_AUTO_ARC_PIP_DOUBLE",          "BB",   "FFFF", ""),
("KEY_AUTO_ARC_PIP_LARGE",           "BC",   "B0",   ""),
("KEY_AUTO_ARC_PIP_SMALL",           "BD",   "AD",   ""),
("KEY_AUTO_ARC_PIP_WIDE",            "BE",   "D0",   ""),
("KEY_AUTO_ARC_PIP_LEFT_TOP",        "BF",   "FFFF", ""),
("KEY_AUTO_ARC_PIP_RIGHT_TOP",       "C0",   "104",  ""),
("KEY_AUTO_ARC_PIP_LEFT_BOTTOM",     "C1",   "FFFF", ""),
("KEY_AUTO_ARC_PIP_RIGHT_BOTTOM",    "C2",   "D1",   ""),
("KEY_AUTO_ARC_PIP_CH_CHANGE",       "C3",   "FFFF", ""),
("KEY_AUTO_ARC_AUTOCOLOR_SUCCESS",   "C4",   "FFFF", ""),
("KEY_AUTO_ARC_AUTOCOLOR_FAIL",      "C5",   "D5",   ""),
("KEY_AUTO_ARC_C_FORCE_AGING",       "C6",   "FC",   ""),
("KEY_AUTO_ARC_USBJACK_INSPECT",     "C7",   "FD",   ""),
("KEY_AUTO_ARC_JACK_IDENT",          "C8",   "FF",   ""),
("KEY_NINE_SEPERATE",                "C9",   "100",  "FE"),
("KEY_ZOOM_IN",                      "CA",   "101",  ""),
("KEY_ZOOM_OUT",                     "CB",   "FFFF", ""),
("KEY_MIC",                          "CC",   "102",  ""),
("KEY_HDMI2",                        "CD",   "FFFF", ""),
("KEY_HDMI3",                        "CE",   "FFFF", ""),
("KEY_AUTO_ARC_CAPTION_KOR",         "CF",   "FFFF", ""),
("KEY_AUTO_ARC_CAPTION_ENG",         "D0",   "F6",   ""),
("KEY_AUTO_ARC_PIP_SOURCE_CHANGE",   "D1",   "FA",   ""),
("KEY_HDMI4",                        "D2",   "F7",   ""),
("KEY_AUTO_ARC_ANTENNA_AIR",         "D3",   "F8",   ""),
("KEY_AUTO_ARC_ANTENNA_CABLE",       "D4",   "F9",   ""),
("KEY_AUTO_ARC_ANTENNA_SATELLITE",   "D5",   "FE",   ""),
("KEY_EXT1",                         "D6",   "10B",  ""),
("KEY_EXT2",                         "D7",   "10B",  ""),
("KEY_EXT3",                         "D8",   "10B",  ""),
("KEY_EXT4",                         "D9",   "10B",  ""),
("KEY_EXT5",                         "DA",   "10B",  ""),
("KEY_EXT6",                         "DB",   "10B",  ""),
("KEY_EXT7",                         "DC",   "10B",  ""),
("KEY_EXT8",                         "DD",   "10B",  ""),
("KEY_EXT9",                         "DE",   "AF",   ""), # IMAGE MODE MOVIE (UN40F5500)
("KEY_EXT10",                        "DF",   "AE",   ""), # IMAGE MODE STANDARD (UN40F5500)
("KEY_EXT11",                        "E0",   "10B",  ""), # STB POWER (UN40F5500)
("KEY_EXT12",                        "E1",   "A9",   ""),
("KEY_EXT13",                        "E2",   "AA",   ""),
("KEY_EXT14",                        "E3",   "AB",   ""), # IMAGE FORMAT 4:3 (UN40F5500)
("KEY_EXT15",                        "E4",   "AC",   ""), # IMAGE FORMAT 16:9 (UN40F5500)
("KEY_EXT16",                        "E5",   "B9",   ""),
("KEY_EXT17",                        "E6",   "10B",  ""),
("KEY_EXT18",                        "E7",   "10B",  ""),
("KEY_EXT19",                        "E8",   "10B",  ""),
("KEY_EXT20",                        "E9",   "BB",   ""), # HDMI 1 (UN40F5500)
("KEY_EXT21",                        "EA",   "10B",  ""),
("KEY_EXT22",                        "EB",   "A5",   ""),
("KEY_EXT23",                        "EC",   "A6",   ""),
("KEY_EXT24",                        "ED",   "A7",   ""),
("KEY_EXT25",                        "EE",   "10B",  ""),
("KEY_EXT26",                        "EF",   "10B",  ""),
("KEY_EXT27",                        "F0",   "10B",  ""), # STB MENU (UN40F5500)
("KEY_EXT28",                        "F1",   "10B",  ""),
("KEY_EXT29",                        "F2",   "10B",  ""),
("KEY_EXT30",                        "F3",   "10B",  ""), # NETFLIX (UN40F5500)
("KEY_EXT31",                        "F4",   "10B",  ""),
("KEY_EXT32",                        "F5",   "10B",  ""),
("KEY_EXT33",                        "F6",   "10B",  ""),
("KEY_EXT34",                        "F7",   "10B",  ""),
("KEY_EXT35",                        "F8",   "10B",  ""),
("KEY_EXT36",                        "F9",   "10B",  ""),
("KEY_EXT37",                        "FA",   "10B",  ""),
("KEY_EXT38",                        "FB",   "A8",   ""),
("KEY_EXT39",                        "FC",   "10B",  ""),
("KEY_EXT40",                        "FD",   "10B",  ""),
("KEY_EXT41",                        "FE",   "10B",  ""),
]

ALIAS_KEYS = [
("BD_KEY_AUDIO",                     "41",   "41",   ""),
("BD_KEY_TITLEMENU",                 "39",   "39",   ""),
("BD_KEY_FULLSCREEN",                "80",   "80",   ""),
("BD_KEY_BONUSVIEW",                 "20",   "20",   ""),
("KEY_PICTURE_SIZE",                 "3E",   "3E",   ""),
("D_KEY_SCROLL_LEFT",                "4C",   "4C",   ""),
("D_KEY_SCROLL_RIGHT",               "41",   "41",   ""),
("D_KEY_SCROLL_UP",                  "3D",   "3D",   ""),
("D_KEY_SCROLL_DOWN",                "57",   "57",   ""),
("D_KEY_BROWSER_BACKWARD",           "45",   "45",   ""),
("D_KEY_BROWSER_FORWARD",            "48",   "48",   ""),
("D_KEY_BROWSER_STOP",               "46",   "46",   ""),
("D_KEY_BROWSER_RELOAD",             "5C",   "5C",   ""),
("D_KEY_BROWSER_URL",                "70",   "70",   ""),
("KEY_INTERACTIVE",                  "93",   "93",   ""),
("FRONTPANNEL_STOP",                 "46",   "46",   ""),
("FRONTPANNEL_PLAY",                 "96",   "96",   ""),
("FRONTPANNEL_ENTER",                "68",   "00",   ""),
("FRONTPANNEL_EJECT",                "5e",   "5E",   ""),
("FRONTPANNEL_POWER",                "02",   "60",   ""),
]


# import json
# for keys in [KEY_CODES, ALIAS_KEYS]:
    # js = {}
    # for k in keys:
        # js[k[0]] = [k[0].replace("KEY_", "").replace("_", " ").title(), ""]
    # #js = sorted(js.items(), key=lambda k: k[1][1])
    # print json.dumps( js, sort_keys=True, indent=2 )

